# Generated by Django 5.0.7 on 2024-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=40)),
                ('game_levels', models.PositiveSmallIntegerField()),
                ('game_description', models.TextField()),
            ],
        ),
    ]
